### ISSUE TITLE
async evaluation

### ISSUE THREAD

**Issue by MasonProtter** [shg/ob-julia-vterm.el#7]
Hey, are there any plans to support async evaluation with this?

**Comment by shg** [comment]
Yes, I'm planning to implement asynchronous evaluation because I need it myself. Simple asynchronous execution of independent blocks is not difficult, but allowing it to work with sessions is tricky. So, the answer is yes, but I don't know yet when it will be ready.

Now that I know that you want it too, I will try to find time to work on it.

**Comment by MasonProtter** [comment]
@shg  Could you give some pointers on how to do the simple version with independent blocks? Why is it that sessions are harder?

**Comment by shg** [comment]
[Ob-async](https://github.com/astahlman/ob-async) implements asynchronous evaluation by launching multiple emacs to run each code blocks. That is simple but it can't support session. To support session, interaction with REPL is necessary like the implementation of [Ob-session-async](https://github.com/jackkamm/ob-session-async), which is now included in Org. Ob-session-async depends on comint, I chose a different approach in ob-julia-vterm since it's on julia-vterm.

I implemented asynchronous evaluation for ob-julia-vterm anyway. It's still experimental but seems working for me. I appreciate your feedback if you have time to try.

**Comment by averter** [comment]
Hello, I just wanted to take the opportunity to mention that when I add ob-julia-vterm to my init.el I cannot run ANY blocks (julia or any other language) asynchronously :-O!!! The blocks output an `error in process sentinel: async-handle-result: Recursive load`. 
I was able to track down that the issue came from ob-julia-vterm. Should I open a new issue to address this? Thanks for the great package, BTW.

**Comment by shg** [comment]
Hi @averter Thank you for trying out ob-julia-vterm and thank you for the report.

> when I add ob-julia-vterm to my init.el I cannot run ANY blocks (julia or any other language) asynchronously `:-O!!!`

Do you mean you can run src blocks of other languages if ob-julia-vterm is not enabled but can't if enabled? Umm that's a terrible issue. Yes please open a new issue. I would very much appreciate detailed information.
